"""add_onboarding_fields

Revision ID: 99426016128c
Revises: 614185049bbf
Create Date: 2026-01-01 20:13:00.189036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99426016128c'
down_revision = '614185049bbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###

